blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('post/<int:pk>/', views.post_full, name='post_full'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
]

nemanjablog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('', include('blog.urls')), #redirect everything that comes into 'http://127.0.0.1:8000/' to blog.urls and looks for further instructions there.
    path('', include('users.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('userpage/', views.userpage, name='userpage'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # foreign key to the user model
    title = models.CharField(max_length=100)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now())
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name= 'comments')
    author = models.CharField(max_length=200)
    text= models.TextField()
    created_date = models.DateTimeField(default=timezone.now())
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment=True
        self.save

    def __str__(self):
        return self.text

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

users/models.py
from django.db import models
from django.contrib.auth.models import User




class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text')

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text')

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True) # this setting is default

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required

def home(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/home.html', {'posts':posts})

def post_full(request,pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_full.html', {'post':post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_full', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_full', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form':form})

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_full', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('post_detail', pk=comment.post.pk)

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from blog.models import Post
from .models import Profile

def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save() # saving the user, hashes the password
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('home')
    else:
        form = UserRegisterForm()

    return render(request, 'users/register.html', {'form':form})


@login_required
def userpage(request):
    return render(request, 'users/userpage.html')

def profile(request, username):
    requser = get_object_or_404(User, username=username)
    requserposts = Post.objects.filter(author=requser)
    return render(request, 'users/profile.html', {'requser':requser, 'requserposts':requserposts})

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Nemanja's Blog</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300&display=swap" rel="stylesheet">
    </head>
    <body>
      <header class="page-header">
        <div class="container">
          {% if user.is_authenticated %}
          <a class="top-menu" href="{% url 'logout' %}">
            <small>Logout</small>
          </a>
          <a href="{% url 'post_new' %}" class="top-menu">
              {% include './icons/patch-plus.svg' %}
              <small>New Post</small>
          </a>
          <a class="top-menu" href="{% url 'users:userpage' %}">
            <small>{{ user.username }}</small>
          </a>
          {% else %}
          <a href="{% url 'login' %}" class="top-menu">
              <small>Login</small>
          </a>
          <a href="{% url 'register' %}" class="top-menu">
              <small>Register</small>
          </a>
          {% endif %}
            <h1><a href="/">Nemanja's Django Blog</a></h1>
        </div>
      </header>

      <main class="container">
        <div class="row">
            <div class="col">
                {% if messages %}
                    {% for message in messages %}
                      <div class="alert alert-{{ message.tags }}">
                          {{ message }}
                      </div>
                    {% endfor %}
                {% endif %}
                {% block content %}
                {% endblock %}
            </div>
        </div>
      </main>
    </body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}
  {% for post in posts %}
      <article class="post">
        {% if user.is_authenticated %}
            {% if user.id == post.author.id %}
                <aside class="actions">
                    <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}">
                      {% include './icons/pencil-square.svg' %}
                    </a>
            {% endif %}
        {% endif %}
        </aside>
        <time class="date">
            {{ post.published_date }}
        </time>
        <h2><a href="{% url 'post_full' pk=post.pk %}">{{ post.title }}</a></h2>
        <p>{{ post.text|linebreaksbr }}</p>
        <a href="{% url 'post_full' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
        <small>Post created by: </small>
        <a href ="{% url 'users:profile' username=post.author %}">
        {{ post.author}}
        </a>
      </article>

  {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
  <h2>New Post</h2>
  <form method = "POST" class="post-form">{% csrf_token %}
    {{ form.as_p }}
  <button type="submit" class='save btn btn-default'>Save</button>
  </form>
{% endblock %}

blog/templates/blog/post_full.html
{% extends 'blog/base.html' %}

{% block content %}
    <article class="post">
      <aside class="actions">
          {% if user.is_authenticated %}
            {% if user.id == post.author.id %}
                <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}">
                  {% include './icons/pencil-square.svg' %}
                </a>
            {% endif %}
          {% endif %}
      </aside>
      <time class="date">
          {{ post.published_date }}
      </time>
      <h2><a href="">{{ post.title }}</a></h2>
      <p>{{ post.text|linebreaksbr }}</p>
      <small>Post created by:</small>
      <a href ="{% url 'users:profile' username=post.author %}">
      {{ post.author}}
      </a>
    </article>
    <hr>
    {% for comment in post.comments.all %}
    {% if user.is_authenticated or comment.approved_comment %}
        <div class="comment">
            <div class="date">
                {{ comment.created_date }}
                {% if not comment.approved_comment %}
                    <a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                    <a class="btn btn-default" href="{% url 'comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                {% endif %}
            </div>
            <strong>{{ comment.author }}</strong>
            <p>{{ comment.text|linebreaks }}</p>
        </div>
        {% endif %}
    {% empty %}
        <p>No comments here yet :(</p>
    {% endfor %}
    {% endblock %}

users/templates/users/login.html
{% extends 'blog/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Log In</legend>
              {{ form|crispy }}
          </fieldset>
          <div class="form-group">
            <button class="btn btn-outline-info" type="submit" name="button">Sign in</button>
          </div>
        </form>
        <div class="border-top pt-3">
          <small class="text-muted">Create an account
          <a class="ml-2" href="{% url 'register' %}">Sign up</a>
          </small>
        </div>
    </div>
{% endblock %}

users/templates/users/logout.html
{% block content %}
    <h3>You have been logged out</h3>
    <div class="content-section">
        <div class="border-top pt-3">
          <small class="text-muted">
          <a href="{% url 'login' %}">Log In Again</a>
          </small>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="content-section">
    <div class="media">
    <img class="rounded-circle account-img" src="{{ requser.profile.image.url }}" >
    <div class="media-body">
      <h2 class="account-heading">{{ requser.username }}</h2>
      <p class="text-secondary">{{ requser.email }}</p>
    </div>
    </div>
    </div>
    <h1>All Posts by {{ requser.username }}</h1>
    {% for post in requserposts %}
        <p><a href="{% url 'post_full' pk=post.pk %}">{{ post.title }}</a></p>
    {% endfor %}
{% endblock content %}

users/templates/users/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Join Now</legend>
              {{ form|crispy }}
          </fieldset>
          <div class="form-group">
            <button class="btn btn-outline-info" type="submit" name="button">Sign Up</button>
          </div>
        </form>
        <div class="border-top pt-3">
          <small class="text-muted">Already have an account ?
          <a class="ml-2" href="{% url 'login' %}">Sign In</a>
          </small>
        </div>
    </div>
{% endblock %}

users/templates/users/userpage.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <div class="media">
    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
    <div class="media-body">
      <h2 class="account-heading">{{ user.username }}</h2>
      <p class="text-secondary">{{ user.email }}</p>
    </div>
    </div>
    </div>
{% endblock content %}